# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: montecarlo/docs/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: montecarlo/docs/requirements.txt