version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - path: .
  requirements_file: montecarlo/docs/requirements.txt

sphinx:
  configuration: montecarlo/docs/conf.py