name: CI

on:
  # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
  # The cookiecutter uses the "--initial-branch" flag when it runs git-init
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/setup-micromamba
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: montecarloPackage/devtools/conda-envs/test_env.yaml
          environment-name: test
          condarc: |
            channels:
              - defaults
          create-args: >- 
            python=${{ matrix.python-version }}

      - name: Install package
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          micromamba list
          
      - name: Set PYTHONPATH (Hardcoded)
        shell: bash -l {0}
        run: |
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/QS1/QS1/montecarloPackage
          echo "PYTHONPATH is: $PYTHONPATH"
          
      - name: Verify package import
        shell: bash -l {0}
        run: |
          echo "PYTHONPATH is: $PYTHONPATH"
          ls -R $GITHUB_WORKSPACE/montecarloPackage
          python -c "import montecarlo" || exit 1   
          
      - name: Run tests
        shell: bash -l {0}
        run: |
          echo "PYTHONPATH is: $PYTHONPATH"
          pytest -v --cov=montecarlo --cov-report=xml --color=yes montecarloPackage/montecarlo/tests/test_montecarlo.py     

      - name: Debug:List Files
        shell: bash
        run: |
          echo "Listing root directory:"
          ls -R $GITHUB_WORKSPACE
          echo "Listing montecarloPackage directory:"
          ls -R $GITHUB_WORKSPACE/montecarloPackage
        

      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

